# Generated by Django 5.1.2 on 2024-10-29 10:44

import sidekick.oembed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=sidekick.oembed.models.Resource.upload_thumbnail)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
