# Generated by Django 5.1.2 on 2024-10-29 21:05

import django.db.models.deletion
import sidekick.newsletter.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Notion ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-published',),
                'get_latest_by': 'published',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.UUIDField(editable=False, unique=True, verbose_name='Notion ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=300)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='newsletter.post')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_url', models.URLField(max_length=255, unique=True, verbose_name='Notion URL')),
                ('media', models.FileField(max_length=255, upload_to=sidekick.newsletter.models.Attachment.upload_media)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='newsletter.post')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Notion ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed', models.DateTimeField()),
                ('excluded_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('sent_posts', models.ManyToManyField(blank=True, related_name='sent_to', to='newsletter.post')),
            ],
            options={
                'ordering': ('-subscribed',),
            },
        ),
    ]
