# Generated by Django 5.1.2 on 2024-10-30 19:26

import sidekick.newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=sidekick.newsletter.models.Post.upload_og_image, verbose_name='Open Graph image'),
        ),
    ]
