# Generated by Django 5.1.2 on 2024-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_post_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(default='Subscribed', max_length=30),
            preserve_default=False,
        ),
    ]
