# Generated by Django 5.1.2 on 2024-10-30 23:13

import django.db.models.deletion
import sidekick.front.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Notion ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=sidekick.front.models.Page.upload_og_image, verbose_name='Open Graph image')),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_url', models.URLField(max_length=255, unique=True, verbose_name='Notion URL')),
                ('media', models.FileField(max_length=255, upload_to=sidekick.front.models.Attachment.upload_media)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='front.page')),
            ],
        ),
    ]
