# Generated by Django 5.1.2 on 2024-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='notion_url',
            field=models.URLField(max_length=512, unique=True, verbose_name='Notion URL'),
        ),
    ]
