# Generated by Django 5.1.2 on 2024-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_attachment_notion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main_menu',
            field=models.BooleanField(default=False),
        ),
    ]
